# Generated by Django 6.0.1 on 2026-01-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, default=2, unique=True),
            preserve_default=False,
        ),
    ]
