# Generated by Django 6.0.1 on 2026-01-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jobapplication_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Saved', 'Saved'), ('Applied', 'Applied'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Saved', max_length=30),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
